
services:
  localhostingapi:
    build: .
    container_name: localhostingapi
    ports:
      - "3003:8000"
    volumes:
      - uploads:/app/app/uploads
      - data:/app/app/data
    environment:
      - PORT=8000
      - SESSION_COOKIE_SECURE=false

volumes:
  uploads:
  data:
